### ISSUE TITLE
Can't connect due to SSL error

### ISSUE THREAD

**Issue by PizzaConsole** [gkiryaziev/Godot-mono.SignalR#1]
this is the error I get, any ideas?

![image](https://user-images.githubusercontent.com/60050783/108176182-e69bcf00-70be-11eb-8cb9-684ac175d27f.png)

**Comment by gkiryaziev** [comment]
Hi. This example worked well with .Net Core 3.1 and Godot 3.2.2. Unfortunately I cannot check it with newer versions now. If you are running the server on localhost, you may want to try using the **http** protocol instead of the **https**.

**Comment by PizzaConsole** [comment]
@gkiryaziev That's the specific problem, I NEED it to work with **https** any idea on how to get that to work?

**Comment by gkiryaziev** [comment]
@PoisnFang Ok, I found some quick solution, however this seems more like a hack than a fix, but it works. Try to add this line of code to _Ready() function. For me it works on localhost and on heroku hosting.
```
System.Net.ServicePointManager.ServerCertificateValidationCallback =
                new System.Net.Security.RemoteCertificateValidationCallback(delegate { return true; });
```

![2021-02-18_001930](https://user-images.githubusercontent.com/8873218/108276223-24146100-7180-11eb-9a57-f2eafd5be474.png)
![2021-02-18_001832](https://user-images.githubusercontent.com/8873218/108276257-32627d00-7180-11eb-89a4-ac29d597642a.png)

**Comment by PoisnFang** [comment]
I dont get it... I have tried and tried and tried that hack for hour cause I found it last night and I CANNOT get it to work.... It just wont connect....
![image](https://user-images.githubusercontent.com/60050783/108278341-1fc45580-7138-11eb-800b-3e3ef73fc498.png)

**Comment by PizzaConsole** [comment]
Scratch that, I update the project to .net 5 and its working now...

**Comment by gkiryaziev** [comment]
Ok, thank you.

**Comment by PizzaConsole** [comment]
@gkiryaziev I am not sure if you'd would be interested in helping me figure out why the same thing wont work with a HttpClient request? Trying it out here: https://github.com/PoisnFang/PokeGodot

**Comment by PizzaConsole** [comment]
@gkiryaziev  So I finally got my code into production and, it is throwing the same error in production....
